name: "stablecoins"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "stablecoins"

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  stablecoins:
    staging:
      +materialized: view
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
# seeds:
#   capstone_project:
#     +column_types:
#       id: integer
#       created_at: timestamp
